# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Executado uma vez por dia à 01:00 UTC (no Brasil, isso pode ser 22:00 dependendo do fuso).
  schedule: [{cron: "0 1 * * *"}]
  # permite rodar manualmente e a cada commit nas branches main ou master
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: lucasdesena
          template: classic
          base: ""
          base_skip: yes
          config_timezone: America/Sao_Paulo
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
